"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Professional_1 = require("./Professional");
var Movie_1 = require("./Movie");
var actor1 = new Professional_1.Proffesional("Carlos", 25, 70, 1.72, false, "Colmbian", 1, "Actor");
var actor2 = new Professional_1.Proffesional("Ana", 40, 70, 1.80, false, "Spanish", 3, "Actress");
var director = new Professional_1.Proffesional("Brandon", 36, 90, 1.70, false, "American", 0, "director");
var writer = new Professional_1.Proffesional("Juan", 52, 90, 1.92, true, "Portuguesse", 2, "Writer");
var movie = new Movie_1.Movie("Hannibal", 2002, "Mexican", "Thriller");
var reparto = [actor1, actor2];
var idioma = "Japanesse";
movie.producer = "Paramount";
movie.actors = reparto;
movie.director = director;
movie.writer = writer;
movie.language = idioma;
movie.isMCU = false;
movie.distributor = "Peliculas Manuel";
movie.mainCharacterName = "Hannibal";
movie.plataforma = "Amazon Prime";
movie.printAllMov();
